export const meta = {
  name: 'boosted-ai-rebrand-v2',
  description: 'Boosted.ai full rebrand v2: territory exploration, adversarial selection, inline-CSS execution',
  phases: [
    { title: 'Explore', detail: 'Naming candidates and three creative territories in parallel' },
    { title: 'Select', detail: 'Adversarial critic picks one territory, writes full CSS execution brief' },
    { title: 'Define', detail: 'Visual identity HTML + brand platform from selected direction' },
    { title: 'Build', detail: 'Consumer homepage, institutional homepage, mobile mockup — pure inline CSS' },
    { title: 'Synthesize', detail: 'What changed vs v1 and why' },
  ],
}

const RFP = 'BOOSTED.AI FULL REBRAND BRIEF\n\nCOMPANY: Boosted.ai, finance-specific AI. 8+ years building finance AI. $61M raised. 300+ institutional clients, $5T+ AUM. 15 patents, SOC 2, FINRA-aware. Named clients: HSBC, RBC, BMO, CIBC, Ameriprise, Invesco, Janus Henderson, Barrow Hanley, Raymond James, Wells Fargo Advisors, Manulife, KeyBank.\n\nKEY PROOF: 8/10 investment professionals prefer Alfa over ChatGPT/Perplexity/Claude. Earnings prep: 40 hours to 20 minutes.\n\nPRODUCTS: Alfa Pro (research tool for PMs/analysts at institutions), Alfa Platform (API + MCP for quants/developers), Alfa consumer (retail app in development).\n\nTHE PIVOT: Building consumer-first for the Daily Reliant Investor (DRI) - serious individual investor who opens the app every trading day. Thesis: institutional advantages should be available to individuals.\n\nWHAT THEY ARE NOT: Not Robinhood/Wealthsimple (basic trading). Not Acorns/Betterment (easy-investing). Not SoFi/Revolut (financial bundles). Closest reference: Public.com - but sharper. One product. One job. Best in the world at it.\n\nEVERYTHING IS ON THE TABLE: company name, logo, product names, visual identity, positioning. Current brand (dark near-black, gold #C19A6B, Hanken Grotesk light) was built for hedge fund sales. May need to change entirely.\n\nDUAL AUDIENCE: Must serve institutional credibility AND DRI accessibility. Neither audience should feel it was built for the other.\n\nREFERENCE BRANDS (CMO-cited): Kalshi (white, bold, confident, editorial, assertive - not typical finance), Ramp (premium white, one strong color, serious finance tool), Harvey (dark but refined editorial, book-quality typography, old money meets new tech).\n\nWHAT TO AVOID: gradients, generic sans-serifs, vague empowerment messaging, fintech cliches (decorative charts, abstract data patterns), anything that looks like the current brand.'

const NO_TOOLS = 'IMPORTANT: Return your complete output as your final text response. Do NOT call Artifact, Write, Bash, or any other tool. Your text response IS the deliverable. The workflow captures it automatically.'

const HTML_RULES = 'CRITICAL HTML RULES - NON-NEGOTIABLE:\n\nThe output renders in a CSP-restricted viewer that BLOCKS ALL EXTERNAL REQUESTS. Any external resource = blank page.\n\n1. NO link rel=stylesheet - no external stylesheets\n2. NO script src= - no external scripts\n3. NO cdn.tailwindcss.com - Tailwind CDN is blocked\n4. NO fonts.googleapis.com - Google Fonts are blocked\n5. NO other external URLs in any src, href, or @import\n\nWHAT YOU MUST DO:\n- Write ALL CSS in a single style block inside head\n- System font stack: font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif\n- Monospace: "JetBrains Mono", "Fira Code", "Courier New", monospace\n- Use CSS custom properties (--variable) for all tokens\n- The page must render perfectly with ZERO network requests\n\nBuild complete, production-quality HTML. Make it long and detailed - show real content, real copy, real interactions. A thin mockup is not acceptable.'

const CSS_BRIEF_TEMPLATE = 'For the CSS execution brief, write a complete :root block with ALL tokens:\n- Background surfaces: --surface-page, --surface-card, --surface-raised, --surface-overlay\n- Text: --text-primary, --text-secondary, --text-muted, --text-disabled\n- Brand: --brand, --brand-hover, --brand-subtle\n- Semantic: --success, --warning, --error\n- Borders: --border, --border-subtle\n- Typography: --font-sans (full system stack), --font-mono, --font-weight-light/regular/medium/bold\n- Type scale: --text-xs through --text-4xl in rem\n- Spacing: --space-1 (4px) through --space-24 (96px)\n- Radii: --radius-sm/md/lg/xl/full\n- Layout: --max-width, --container-padding\n\nAlso specify: SIGNATURE VISUAL GESTURE, TYPOGRAPHY RULES, BUTTON STYLE, CARD/PANEL TREATMENT, BRAND MARK DIRECTION.'

phase('Explore')

const [territoriesOutput, namingOutput] = await parallel([

  () => agent('You are a creative director on the Boosted.ai full rebrand. Your mandate: develop THREE genuinely different creative territories - visual + strategic directions the brand could take.\n\n' + RFP + '\n\nCURRENT BRAND TO MOVE AWAY FROM: Background near-black (#080808), accent gold (#C19A6B), Hanken Grotesk 300/400/500 light weight. Feel: fintech-dark SaaS, institutional, cold.\n\nYOUR MANDATE: Three territories that are different from each other and from the current brand. Informed by Kalshi, Ramp, Harvey but not copies of them.\n\nFor each territory provide:\n- TERRITORY NAME (3-5 words, evocative)\n- TAGLINE (1 sentence positioning statement this enables)\n- VISUAL DIRECTION: background choice + rationale, primary text color, ONE accent color (name it, give hex, explain why), typography approach, signature visual gesture (the one unmistakable element), what a homepage hero looks like in this direction\n- EMOTIONAL CHARACTER: 3-5 adjectives + 2-3 sentences on the feeling\n- STRATEGIC FIT: why this works for both institutional and DRI audiences\n- COMPETITIVE DIFFERENTIATION: vs Bloomberg, FactSet, Robinhood, Public.com\n- RISK/WEAKNESS: honest case against this direction\n\nTERRITORY DIRECTIONS TO EXPLORE:\n\nTerritory 1 - LIGHT EDITORIAL: Confident, editorial, light. White or near-white background. Strong black typography. One surgical accent color that is NOT gold. Why would the world\'s best finance AI choose to not be dark? Think: a serious financial publication redesigned as software.\n\nTerritory 2 - DARK REFINED: Dark but with book-quality typography - not tech-dark. Think vintage Financial Times or The Economist digital, modernized. Serif elements as a key ingredient. Editorial layout. The difference from the current brand: the typographic language is completely different - refined, slow, considered.\n\nTerritory 3 - UNEXPECTED: Break the finance playbook entirely. Unexpected color choice (not navy, not gold, not green). Extreme graphic system. Or ultra-minimal. What would a great designer with no finance background do if they understood this product deeply?\n\n' + NO_TOOLS, {label: 'territory-developer', phase: 'Explore'}),

  () => agent('You are a naming strategist on the Boosted.ai full rebrand. Both "Boosted.ai" (company name) AND "Alfa" (product name) are candidates to be replaced.\n\n' + RFP + '\n\nSECTION 1 - CURRENT NAME AUDIT\nEvaluate "Boosted.ai" and "Alfa" honestly:\n- Memorability and pronounceability\n- Category fit (finance AI, institutional + consumer)\n- International viability\n- What each signals to institutional buyer vs DRI consumer\n- Recommendation: keep, modify, or replace each?\n\nSECTION 2 - NAME EXPLORATION\nExplore 10 candidates across:\n1. Short action/precision words (like Ramp)\n2. Human advisor/partner names (like Harvey)\n3. Invented/coined names (like Kalshi)\n4. Financial/market concepts reimagined\n5. Unexpected conceptual names\n\nFor each: name, category, 2-3 sentence rationale, risks, domain likelihood.\n\nSECTION 3 - ARCHITECTURE RECOMMENDATION\nSingle brand, house of brands, or endorsed architecture? With rationale.\n\nSECTION 4 - FINAL RECOMMENDATIONS\nTop 3 name recommendations with full rationale. For each: how it works institutionally, how it works for DRI, how it pairs with a product name.\n\n' + NO_TOOLS, {label: 'naming-strategist', phase: 'Explore'}),

])

phase('Select')

const criticOutput = await agent('You are the adversarial critic on the Boosted.ai rebrand. You have received three creative territories and naming analysis. Ruthlessly evaluate all three, select exactly ONE, write the complete CSS execution brief for all downstream agents.\n\n' + RFP + '\n\nTERRITORIES:\n' + territoriesOutput + '\n\nNAMING:\n' + namingOutput + '\n\nEVALUATION CRITERIA:\n- Does it genuinely solve the dual-audience problem (institutional + DRI)?\n- Is it differentiated from Bloomberg, Robinhood, Public.com, and the current brand?\n- Can it work in both B2B (pitch decks, enterprise sales) and B2C (app, social ads)?\n- Is the visual language coherent and distinctive enough to own?\n- Is it brave enough to be interesting while safe enough for a real company?\n\nOUTPUT:\n\n## TERRITORY EVALUATION\n\n### Territory 1: [Name]\n[2-3 sentences verdict]\nScore: X/10\n\n### Territory 2: [Name]\n[2-3 sentences verdict]\nScore: X/10\n\n### Territory 3: [Name]\n[2-3 sentences verdict]\nScore: X/10\n\n## SELECTED TERRITORY: [Name]\n[3-4 sentences explaining why this beats the others]\n\n## NAMING RECOMMENDATION\nCompany: [X]. Consumer product: [Y]. Institutional suite: [Z].\n\n## CSS EXECUTION BRIEF\nWrite the complete :root CSS custom properties block - no markdown fences, just the raw CSS. Then the additional design specs:\n\n' + CSS_BRIEF_TEMPLATE + '\n\n' + NO_TOOLS, {label: 'adversarial-critic', phase: 'Select'})

phase('Define')

const [identityOutput, platformOutput] = await parallel([

  () => agent('You are the visual identity designer. Build a comprehensive HTML visual identity reference page using ONLY the CSS tokens from the execution brief.\n\n' + HTML_RULES + '\n\nEXECUTION BRIEF:\n' + criticOutput + '\n\nBUILD a complete self-contained HTML visual identity reference with these sections:\n\n1. HEADER - brand mark (selected name in brand typographic style), territory name, tagline\n2. COLOR SYSTEM - every --variable as a swatch with name, hex, use case description\n3. TYPOGRAPHY SCALE - each size (--text-xs through --text-4xl) with a real sentence, showing weight variations\n4. BRAND MARK - logotype in multiple configs: on page background, on brand color, reversed, small\n5. SPACING REFERENCE - visual spacing scale\n6. COMPONENTS - buttons (primary/secondary/ghost), inputs, badges, dividers - all using only CSS variables\n7. SIGNATURE VISUAL GESTURE - full-width demonstration of the brand\'s unmistakable element from the brief\n8. APPLICATION PREVIEWS - 3 small panels: a mobile screen, a print ad concept, a presentation slide\n\nSTANDARDS:\n- Real brand copy, not lorem ipsum\n- Every element uses only --variable tokens from the :root block in the brief\n- The PAGE ITSELF exemplifies the selected territory\n- Minimum 600 lines of clean HTML\n- Full utility CSS section with classes derived from tokens\n\n' + NO_TOOLS + '\n\nReturn the complete HTML file as your final text response.', {label: 'identity-designer', phase: 'Define'}),

  () => agent('You are the brand platform writer. Build the complete verbal identity and brand platform.\n\nEXECUTION BRIEF (SELECTED TERRITORY + NAME):\n' + criticOutput + '\n\nNAMING ANALYSIS:\n' + namingOutput + '\n\n' + RFP + '\n\nDELIVERABLE: Complete brand platform in markdown.\n\n## Brand Purpose\nWhy this company exists beyond making money. 3-5 sentences.\n\n## Brand Beliefs\n5-7 conviction statements. "We believe [X]." format.\n\n## Brand Positioning\n- Category: what this brand defines or redefines\n- For: specific audience description\n- Who: the insight about them that shapes everything\n- Versus: who and what the brand is against\n- The brand IS: 3-5 defining characteristics\n- The brand is NOT: 3-5 clear rejections\n\n## Tone of Voice\n4 characteristics. Each: name it, 2-3 sentences, one DOES example and one DOESN\'T example.\n\n## Messaging Framework\n- Primary message (7 words or fewer)\n- Support messages (3, one sentence each)\n- Proof points (5-7 specific, verifiable)\n- Emotional message (what to feel, not know)\n\n## Naming System\nFrom the critic\'s recommendation: company name rationale, consumer product rationale, institutional suite rationale, naming rules for future products.\n\n## Copy Executions\nReal copy for 8 surfaces:\n1. App hero headline + subhead (consumer/DRI)\n2. App hero headline + subhead (institutional)\n3. App store description (150 words)\n4. LinkedIn ad (headline + 2-line body + CTA)\n5. Homepage meta description (155 chars)\n6. Sales email subject + opening paragraph\n7. Onboarding welcome (first thing new user sees)\n8. Brand manifesto (200-300 words, brand speaking)\n\n' + NO_TOOLS, {label: 'brand-platform', phase: 'Define'}),

])

phase('Build')

const [consumerOutput, institutionalOutput, mobileOutput] = await parallel([

  () => agent('You are building the consumer-facing homepage for the rebrand. Target: Daily Reliant Investor (DRI) - serious individual investor who opens the app every trading day.\n\n' + HTML_RULES + '\n\nEXECUTION BRIEF:\n' + criticOutput + '\n\nBRAND PLATFORM:\n' + platformOutput + '\n\nBUILD a complete consumer homepage - nav through footer. A marketing site that makes a DRI feel understood and want to sign up immediately.\n\nRequired sections:\n1. NAV - logo/wordmark + minimal nav links + CTA button\n2. HERO - strongest possible headline from brand platform copy, subhead, primary CTA, supporting visual element (NOT a stock chart)\n3. THE PROBLEM - what is broken about how individual investors work today\n4. THE PRODUCT - what this does, explained plainly and precisely. 3 core capabilities.\n5. PROOF - 8/10 institutional preference stat, 40h to 20min, "if it\'s good enough for HSBC..." framing\n6. HOW IT WORKS - 3-step flow showing daily use\n7. TESTIMONIALS - 2-3 realistic fabricated DRI testimonials (not sycophantic)\n8. WAITLIST/CTA - email signup section\n9. FOOTER - logo, legal disclaimer, links\n\nSTANDARDS: Use brand platform copy. Show brand voice in every line. All CSS from :root tokens. No external resources. Min 400 lines.\n\n' + NO_TOOLS + '\n\nReturn the complete HTML file as your final text response.', {label: 'consumer-homepage', phase: 'Build'}),

  () => agent('You are building the institutional homepage for the rebrand. Target: portfolio managers, analysts, CIOs at hedge funds, asset managers, wealth management firms.\n\n' + HTML_RULES + '\n\nEXECUTION BRIEF:\n' + criticOutput + '\n\nBRAND PLATFORM:\n' + platformOutput + '\n\nBUILD a complete institutional B2B marketing page - nav through footer.\n\nRequired sections:\n1. NAV - logo/wordmark + Products/Clients/Platform/About + "Request Demo" CTA\n2. HERO - institutional headline (authority not aspiration), client logos visible, 300+ clients / $5T+ AUM\n3. CLIENT STRIP - HSBC, RBC, BMO, CIBC, Ameriprise, Invesco, Janus Henderson, Barrow Hanley, Raymond James, Wells Fargo Advisors\n4. PRODUCT OVERVIEW - research tool + API/developer platform. What job does each do?\n5. CAPABILITY DEEP-DIVE - Earnings Intelligence: 40h to 20min. How the AI works. Vs Bloomberg/FactSet.\n6. PROOF STATS - 8/10 preference, time stat, client count, AUM, patents. Stat grid.\n7. SECURITY - SOC 2, FINRA-aware, data handling.\n8. PLATFORM/API - brief section for quant teams\n9. DEMO CTA - Request a demo with form concept\n10. FOOTER - full footer with links and legal\n\nSTANDARDS: Authoritative tone. Specific, verifiable claims only. All CSS from :root tokens. No external resources. Min 400 lines.\n\n' + NO_TOOLS + '\n\nReturn the complete HTML file as your final text response.', {label: 'institutional-homepage', phase: 'Build'}),

  () => agent('You are building three mobile app screen mockups for the consumer app rebrand.\n\n' + HTML_RULES + '\n\nEXECUTION BRIEF:\n' + criticOutput + '\n\nBRAND PLATFORM:\n' + platformOutput + '\n\nBUILD a showcase page with three phone-frame mockups rendered purely in CSS/HTML.\n\nPHONE FRAME SPECS: width 320px, height 693px, border-radius 44px, thin border using --border token, status bar at top (time + status icons), home indicator bar at bottom.\n\nSCREEN 1 - DASHBOARD: Personalized greeting. Portfolio value (large, prominent). Today\'s performance (+/- %). Intelligence feed: 3-4 signal cards (ticker, signal type, description, price change). Bottom tab nav. Apply the selected territory inside the phone - if light brand, light screen; if dark, dark.\n\nSCREEN 2 - INTELLIGENCE DETAIL: Back navigation. Ticker + company headline. Signal type badge. AI analysis (3-4 sentences, specific financial language, real companies/numbers). Metrics grid (revenue estimate, EPS, analyst consensus, options activity). Two action buttons.\n\nSCREEN 3 - AI CHAT: Chat header with product name. One realistic financial Q&A pair (real market language). Second Q&A pair. Disclaimer text. Input bar with send button. Show brand voice in AI responses - intelligent and precise, not chatty.\n\nPAGE LAYOUT: Brand name + "Mobile Experience" title. Three phones side by side. Caption under each. Footer.\n\nSTANDARDS: Real financial content. Territory consistently applied inside frames. All CSS from :root. No external resources.\n\n' + NO_TOOLS + '\n\nReturn the complete HTML file as your final text response.', {label: 'mobile-mockup', phase: 'Build'}),

])

phase('Synthesize')

const synthesisOutput = await agent('You are the strategic synthesizer. Write the final strategic summary of this rebrand.\n\nSELECTED TERRITORY AND NAMING:\n' + criticOutput + '\n\nBRAND PLATFORM:\n' + platformOutput + '\n\nORIGINAL BRIEF:\n' + RFP + '\n\nCONTEXT: This is v2 of an AI-led rebrand attempt. V1 applied the existing brand system (dark + gold) without questioning it. V2 started from scratch: three different territories, adversarial selection, execution from the selected direction only.\n\nDELIVERABLE: Two documents in a single response.\n\nDOCUMENT 1: WHAT CHANGED AND WHY (for the CMO)\n\n## What V1 Got Wrong\n3-4 specific mistakes in the first pass (name the specific choices and why they were wrong)\n\n## What V2 Chose and Why\n- Selected territory: describe plainly, what it looks/sounds/feels like\n- Naming recommendation: what changed and why\n- Brand platform shift: how positioning and voice changed from v1\n\n## The Key Strategic Bets\n3-4 bets this brand makes that competitors would not make\n\n## Risks and Trade-offs\nWhat does this direction give up? Who might not respond?\n\n## If You Do Nothing\nWhat happens to Boosted.ai if this rebrand does not happen?\n\nDOCUMENT 2: ONE-PAGE FOR JOSH AND MURRAY\n(Josh Pantony = CEO, Murray = CFO/partner)\n\n1. What are we recommending and what does it look like?\n2. Core strategic logic (2-3 sentences max)\n3. What would Studio Freight add over this AI work?\n4. The decision\n\nTone: direct, no brand-speak, like a memo from a CMO who has done their homework.\n\n' + NO_TOOLS, {label: 'synthesizer', phase: 'Synthesize'})

return {
  territories: territoriesOutput,
  naming: namingOutput,
  critic: criticOutput,
  identity: identityOutput,
  platform: platformOutput,
  consumer: consumerOutput,
  institutional: institutionalOutput,
  mobile: mobileOutput,
  synthesis: synthesisOutput,
}
